from .academic_rank import academicRank
from .city import city
from .country import country
from .department import department
from .fund import fund
from .position import position
from .position_type import positionType
from .prof_interest import profInterest
from .professor import professor
from .research_interest import researchInterest
from .university import university
from .user import user
