from .academic_rank import academic_rank
from .city import city
from .country import country
from .department import department
from .fund import fund
from .position import position
from .position_type import position_type
from .prof_interest import prof_interest
from .professor import professor
from .research_interest import research_interest
from .university import university
from .user import user
