from src.database.session import Base
from src.models.academic_rank import AcademicRank
from src.models.city import City
from src.models.country import Country
from src.models.department import Department
from src.models.fund import Fund
from src.models.position import Position
from src.models.position_type import PositionType
from src.models.prof_interest import ProfInterest
from src.models.professor import Professor
from src.models.research_interest import ResearchInterest
from src.models.university import University
from src.models.user import User
