from datetime import datetime

from sqlalchemy.orm import Session

from src import crud, schemas
from src.database import base  # keep


def init_db(db: Session):
    add_academic_rank_seed_data(db)
    add_country_seed_data(db)
    add_city_seed_data(db)
    add_department_seed_data(db)
    add_fund_seed_data(db)
    add_position_type_seed_data(db)
    add_university_seed_data(db)
    add_research_interest_seed_data(db)
    add_professor_seed_data(db)


academic_rank_seed_data = [
    schemas.AcademicRankCreate(
        academic_rank_title="Lecturer",
    ),
    schemas.AcademicRankCreate(
        academic_rank_title="Senior Lecturer",
    ),
    schemas.AcademicRankCreate(
        academic_rank_title="Assistant Professor",
    ),
    schemas.AcademicRankCreate(
        academic_rank_title="Associate Professor",
    ),
    schemas.AcademicRankCreate(
        academic_rank_title="Full Professor",
    ),
    schemas.AcademicRankCreate(
        academic_rank_title="Instructor",
    ),
    schemas.AcademicRankCreate(
        academic_rank_title="Teaching Professor",
    ),
]


def add_academic_rank_seed_data(db: Session):
    if not crud.academic_rank.get_all(db):
        for data in academic_rank_seed_data:
            crud.academic_rank.create(db, data)


country_seed_data = [
    schemas.CountryCreate(
        country_name="US",
    ),
    schemas.CountryCreate(
        country_name="Canada",
    ),
    schemas.CountryCreate(
        country_name="England",
    ),
    schemas.CountryCreate(
        country_name="Germany",
    ),
    schemas.CountryCreate(
        country_name="Italy",
    ),
    schemas.CountryCreate(
        country_name="Australia",
    ),
    schemas.CountryCreate(
        country_name="Turkey",
    ),
    schemas.CountryCreate(
        country_name="China",
    ),
]


def add_country_seed_data(db: Session):
    if not crud.country.get_all(db):
        for data in country_seed_data:
            crud.country.create(db, data)


city_seed_data = [
    schemas.CityCreate(
        city_name="North Dakota",
        country_id=1,
    ),
    schemas.CityCreate(
        city_name="California",
        country_id=1,
    ),
    schemas.CityCreate(
        city_name="Texas",
        country_id=1,
    ),
    schemas.CityCreate(
        city_name="Alabama",
        country_id=1,
    ),
    schemas.CityCreate(
        city_name="Minnesota",
        country_id=1,
    ),
    schemas.CityCreate(
        city_name="Emory",
        country_id=1,
    ),
    schemas.CityCreate(
        city_name="Concordia",
        country_id=1,
    ),
    schemas.CityCreate(
        city_name="Arizona",
        country_id=1,
    ),
    schemas.CityCreate(
        city_name="Boston",
        country_id=1,
    ),
    schemas.CityCreate(
        city_name="Troy",
        country_id=1,
    ),
    schemas.CityCreate(
        city_name="Massachusetts",
        country_id=1,
    ),
    schemas.CityCreate(
        city_name="New York",
        country_id=1,
    ),
    schemas.CityCreate(
        city_name="Baltimore",
        country_id=1,
    ),
    schemas.CityCreate(
        city_name="Ithaca",
        country_id=1,
    ),
    schemas.CityCreate(
        city_name="Cambridge",
        country_id=3,
    ),
    schemas.CityCreate(
        city_name="Oxford",
        country_id=3,
    ),
    schemas.CityCreate(
        city_name="Manchester",
        country_id=3,
    ),
    schemas.CityCreate(
        city_name="Birmingham",
        country_id=3,
    ),
    schemas.CityCreate(
        city_name="London",
        country_id=3,
    ),
    schemas.CityCreate(
        city_name="Durtham",
        country_id=3,
    ),
    schemas.CityCreate(
        city_name="Berlin",
        country_id=4,
    ),
    schemas.CityCreate(
        city_name="Munich",
        country_id=4,
    ),
    schemas.CityCreate(
        city_name="Heidelberg",
        country_id=4,
    ),
    schemas.CityCreate(
        city_name="Aachen",
        country_id=4,
    ),
    schemas.CityCreate(
        city_name="Karlsruhe",
        country_id=4,
    ),
    schemas.CityCreate(
        city_name="Montreal",
        country_id=2,
    ),
    schemas.CityCreate(
        city_name="Toronto",
        country_id=2,
    ),
    schemas.CityCreate(
        city_name="British Columbia",
        country_id=2,
    ),
]


def add_city_seed_data(db: Session):
    if not crud.city.get_all(db):
        for data in city_seed_data:
            crud.city.create(db, data)


department_seed_data = [
    schemas.DepartmentCreate(
        department_name="Electrical and Computer Engineering",
    ),
    schemas.DepartmentCreate(
        department_name="Mechanical Engineering",
    ),
    schemas.DepartmentCreate(
        department_name="Civil and Environmental Engineering",
    ),
    schemas.DepartmentCreate(
        department_name="Computer Science",
    ),
]


def add_department_seed_data(db: Session):
    if not crud.department.get_all(db):
        for data in department_seed_data:
            crud.department.create(db, data)


fund_seed_data = [
    schemas.FundCreate(
        fund_type="Full Found",
    ),
    schemas.FundCreate(
        fund_type="Half Fund",
    ),
    schemas.FundCreate(
        fund_type="Self Fund",
    ),
]


def add_fund_seed_data(db: Session):
    if not crud.fund.get_all(db):
        for data in fund_seed_data:
            crud.fund.create(db, data)


position_type_seed_data = [
    schemas.PositionTypeCreate(
        position_type="Bachelor",
    ),
    schemas.PositionTypeCreate(
        position_type="MSc",
    ),
    schemas.PositionTypeCreate(
        position_type="PHD",
    ),
    schemas.PositionTypeCreate(
        position_type="Post Doc",
    ),
]


def add_position_type_seed_data(db: Session):
    if not crud.position_type.get_all(db):
        for data in position_type_seed_data:
            crud.position_type.create(db, data)


university_seed_data = [
    schemas.UniversityCreate(
        city_id=1,
        university_name="North Dakota State University",
        internationals_as_ta=True,
        fall_deadline=datetime(2024, 9, 29),
        winter_deadline=datetime(2024, 12, 29),
    ),
    schemas.UniversityCreate(
        city_id=2,
        university_name="University of California, Irvine",
        internationals_as_ta=True,
        fall_deadline=datetime(2024, 9, 29),
        winter_deadline=datetime(2024, 12, 29),
    ),
    schemas.UniversityCreate(
        city_id=3,
        university_name="University of Texas at Dallas",
        internationals_as_ta=True,
        fall_deadline=datetime(2024, 9, 29),
        winter_deadline=datetime(2024, 12, 29),
    ),
    schemas.UniversityCreate(
        city_id=4,
        university_name="University of Alabama at Birmingham, AL",
        internationals_as_ta=True,
        fall_deadline=datetime(2024, 9, 29),
        winter_deadline=datetime(2024, 12, 29),
    ),
    schemas.UniversityCreate(
        city_id=5,
        university_name="University of Minnesota, Twin Cities, Minneapolis, MN",
        internationals_as_ta=True,
        fall_deadline=datetime(2024, 9, 29),
        winter_deadline=datetime(2024, 12, 29),
    ),
    schemas.UniversityCreate(
        city_id=3,
        university_name="University of Texas at Austin",
        internationals_as_ta=True,
        fall_deadline=datetime(2024, 9, 29),
        winter_deadline=datetime(2024, 12, 29),
    ),
    schemas.UniversityCreate(
        city_id=6,
        university_name="Emory University",
        internationals_as_ta=True,
        fall_deadline=datetime(2024, 9, 29),
        winter_deadline=datetime(2024, 12, 29),
    ),
    schemas.UniversityCreate(
        city_id=7,
        university_name="Concordia University",
        internationals_as_ta=True,
        fall_deadline=datetime(2024, 9, 29),
        winter_deadline=datetime(2024, 12, 29),
    ),
    schemas.UniversityCreate(
        city_id=8,
        university_name="Arizona State University, Tempe, AZ",
        internationals_as_ta=True,
        fall_deadline=datetime(2024, 9, 29),
        winter_deadline=datetime(2024, 12, 29),
    ),
    schemas.UniversityCreate(
        city_id=9,
        university_name="Northeastern University, Boston, MA",
        internationals_as_ta=True,
        fall_deadline=datetime(2024, 9, 29),
        winter_deadline=datetime(2024, 12, 29),
    ),
    schemas.UniversityCreate(
        city_id=2,
        university_name="University of California, Riverside",
        internationals_as_ta=True,
        fall_deadline=datetime(2024, 9, 29),
        winter_deadline=datetime(2024, 12, 29),
    ),
    schemas.UniversityCreate(
        city_id=2,
        university_name="University of Southern California, LA",
        internationals_as_ta=True,
        fall_deadline=datetime(2024, 9, 29),
        winter_deadline=datetime(2024, 12, 29),
    ),
    schemas.UniversityCreate(
        city_id=10,
        university_name="Rensselaer Polytechnic Institute, Troy, NY",
        internationals_as_ta=True,
        fall_deadline=datetime(2024, 9, 29),
        winter_deadline=datetime(2024, 12, 29),
    ),
    schemas.UniversityCreate(
        city_id=11,
        university_name="Massachusetts Institute of Technology",
        internationals_as_ta=True,
        fall_deadline=datetime(2024, 9, 29),
        winter_deadline=datetime(2024, 12, 29),
    ),
    schemas.UniversityCreate(
        city_id=12,
        university_name="New York University, New York, NY",
        internationals_as_ta=True,
        fall_deadline=datetime(2024, 9, 29),
        winter_deadline=datetime(2024, 12, 29),
    ),
    schemas.UniversityCreate(
        city_id=13,
        university_name="Johns Hopkins University",
        internationals_as_ta=True,
        fall_deadline=datetime(2024, 9, 29),
        winter_deadline=datetime(2024, 12, 29),
    ),
    schemas.UniversityCreate(
        city_id=14,
        university_name="Cornell University, Ithaca, NY",
        internationals_as_ta=True,
        fall_deadline=datetime(2024, 9, 29),
        winter_deadline=datetime(2024, 12, 29),
    ),
    schemas.UniversityCreate(
        city_id=8,
        university_name="Anglia Ruskin University",
        internationals_as_ta=True,
        fall_deadline=datetime(2024, 9, 29),
        winter_deadline=datetime(2024, 12, 29),
    ),
    schemas.UniversityCreate(
        city_id=15,
        university_name="Cambridge University",
        internationals_as_ta=True,
        fall_deadline=datetime(2024, 9, 29),
        winter_deadline=datetime(2024, 12, 29),
    ),
    schemas.UniversityCreate(
        city_id=16,
        university_name="Oxford University",
        internationals_as_ta=True,
        fall_deadline=datetime(2024, 9, 29),
        winter_deadline=datetime(2024, 12, 29),
    ),
    schemas.UniversityCreate(
        city_id=17,
        university_name="Manchester University",
        internationals_as_ta=True,
        fall_deadline=datetime(2024, 9, 29),
        winter_deadline=datetime(2024, 12, 29),
    ),
    schemas.UniversityCreate(
        city_id=18,
        university_name="Birmingham University",
        internationals_as_ta=True,
        fall_deadline=datetime(2024, 9, 29),
        winter_deadline=datetime(2024, 12, 29),
    ),
    schemas.UniversityCreate(
        city_id=19,
        university_name="London University",
        internationals_as_ta=True,
        fall_deadline=datetime(2024, 9, 29),
        winter_deadline=datetime(2024, 12, 29),
    ),
    schemas.UniversityCreate(
        city_id=20,
        university_name="Durtham University",
        internationals_as_ta=True,
        fall_deadline=datetime(2024, 9, 29),
        winter_deadline=datetime(2024, 12, 29),
    ),
    schemas.UniversityCreate(
        city_id=22,
        university_name="Technical University of Munich",
        internationals_as_ta=True,
        fall_deadline=datetime(2024, 9, 29),
        winter_deadline=datetime(2024, 12, 29),
    ),
    schemas.UniversityCreate(
        city_id=22,
        university_name="Ludwig Maximilian University of Munich",
        internationals_as_ta=True,
        fall_deadline=datetime(2024, 9, 29),
        winter_deadline=datetime(2024, 12, 29),
    ),
    schemas.UniversityCreate(
        city_id=21,
        university_name="Free University of Berlin",
        internationals_as_ta=True,
        fall_deadline=datetime(2024, 9, 29),
        winter_deadline=datetime(2024, 12, 29),
    ),
    schemas.UniversityCreate(
        city_id=21,
        university_name="Technical University Berlin",
        internationals_as_ta=True,
        fall_deadline=datetime(2024, 9, 29),
        winter_deadline=datetime(2024, 12, 29),
    ),
    schemas.UniversityCreate(
        city_id=25,
        university_name="Karlsruhe Institute of Technology",
        internationals_as_ta=True,
        fall_deadline=datetime(2024, 9, 29),
        winter_deadline=datetime(2024, 12, 29),
    ),
    schemas.UniversityCreate(
        city_id=21,
        university_name="Humboldt University of Berlin",
        internationals_as_ta=True,
        fall_deadline=datetime(2024, 9, 29),
        winter_deadline=datetime(2024, 12, 29),
    ),
    schemas.UniversityCreate(
        city_id=23,
        university_name="Heidelberg University",
        internationals_as_ta=True,
        fall_deadline=datetime(2024, 9, 29),
        winter_deadline=datetime(2024, 12, 29),
    ),
    schemas.UniversityCreate(
        city_id=24,
        university_name="RWTH Aachen University",
        internationals_as_ta=True,
        fall_deadline=datetime(2024, 9, 29),
        winter_deadline=datetime(2024, 12, 29),
    ),
    schemas.UniversityCreate(
        city_id=27,
        university_name="University of Toronto",
        internationals_as_ta=True,
        fall_deadline=datetime(2024, 9, 29),
        winter_deadline=datetime(2024, 12, 29),
    ),
    schemas.UniversityCreate(
        city_id=28,
        university_name="University of British Columbia",
        internationals_as_ta=True,
        fall_deadline=datetime(2024, 9, 29),
        winter_deadline=datetime(2024, 12, 29),
    ),
    schemas.UniversityCreate(
        city_id=26,
        university_name="McGill University",
        internationals_as_ta=True,
        fall_deadline=datetime(2024, 9, 29),
        winter_deadline=datetime(2024, 12, 29),
    ),
]


def add_university_seed_data(db: Session):
    if not crud.university.get_all(db):
        for data in university_seed_data:
            crud.university.create(db, data)


research_interest_seed_data = [
    schemas.ResearchInterestCreate(
        research_interest_name="Artificial Intelligence",
        description="",
    ),
    schemas.ResearchInterestCreate(
        research_interest_name="Machine Learning",
        description="",
    ),
    schemas.ResearchInterestCreate(
        research_interest_name="Mechatronics",
        description="",
    ),
    schemas.ResearchInterestCreate(
        research_interest_name="Nonlinear System Modeling",
        description="",
    ),
    schemas.ResearchInterestCreate(
        research_interest_name="Smart Grids",
        description="",
    ),
    schemas.ResearchInterestCreate(
        research_interest_name="Power Electronics",
        description="",
    ),
    schemas.ResearchInterestCreate(
        research_interest_name="Energy System Optimization",
        description="",
    ),
    schemas.ResearchInterestCreate(
        research_interest_name="Renewable Energy",
        description="",
    ),
    schemas.ResearchInterestCreate(
        research_interest_name="Hydrology",
        description="",
    ),
    schemas.ResearchInterestCreate(
        research_interest_name="Construction Management",
        description="",
    ),
    schemas.ResearchInterestCreate(
        research_interest_name="Data Science",
        description="",
    ),
]


def add_research_interest_seed_data(db: Session):
    if not crud.research_interest.get_all(db):
        for data in research_interest_seed_data:
            crud.research_interest.create(db, data)


professor_seed_data = [
    # Pariya - 25 US Data
    schemas.ProfessorCreate(
        professor_f_name="Sulaymon",
        professor_m_name="",
        professor_l_name="Eshkabilov",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=1,
        department_id=2,
        email="sulaymon.eshkabilov@ndsu.edu",
        linkedin="https://www.linkedin.com/in/sulaymon-eshkabilov-3778745/",
        google_scholar="https://scholar.google.com/citations?hl=en&user=edIEM5oAAAAJ",
        h_index=13,
        profile_uni_site="https://www.ndsu.edu/aben/faculty_staff/dr_sulaymon_eshkabilov_assistant_professor/",
        education_description="",
        extra_description="",
        academic_rank_id=3,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Yanning",
        professor_m_name="",
        professor_l_name="Shen",
        prof_gender=True,
        prof_code_in_uni=None,
        university_id=2,
        department_id=2,
        email="yannings@uci.edu",
        linkedin="https://www.linkedin.com/in/yanning-shen-a4b27061/",
        google_scholar="https://scholar.google.com/citations?hl=en&user=MfzntAIAAAAJ",
        h_index=23,
        profile_uni_site="https://engineering.uci.edu/users/yanning-shen",
        education_description="",
        extra_description="",
        academic_rank_id=3,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Berrak",
        professor_m_name="",
        professor_l_name="Sisman",
        prof_gender=True,
        prof_code_in_uni=None,
        university_id=3,
        department_id=2,
        email="berrak.sisman@utdallas.edu",
        linkedin="https://www.linkedin.com/in/berraksisman/",
        google_scholar="https://scholar.google.com/citations?hl=en&user=inTpYLkAAAAJ",
        h_index=23,
        profile_uni_site="https://ece.utdallas.edu/staff/sisman/",
        education_description="",
        extra_description="",
        academic_rank_id=3,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Edward",
        professor_m_name="",
        professor_l_name="Sazonov",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=4,
        department_id=2,
        email="yannings@uci.edu",
        linkedin="https://www.linkedin.com/in/edward-sazonov/",
        google_scholar="https://scholar.google.com/citations?hl=en&user=HE_1__kAAAAJ",
        h_index=45,
        profile_uni_site="https://eng.ua.edu/eng-directory/dr-edward-sazonov/",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Rui",
        professor_m_name="",
        professor_l_name="Cheng",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=5,
        department_id=2,
        email="ruicheng@umn.edu",
        linkedin="",
        google_scholar="",
        h_index=0,
        profile_uni_site="https://ruillercoaster.github.io/EnvironmentalSensingLab/",
        education_description="",
        extra_description="",
        academic_rank_id=3,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Azra",
        professor_m_name="",
        professor_l_name="Ismail",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=7,
        department_id=2,
        email="azra.ismail@emory.edu",
        linkedin="https://www.linkedin.com/in/azra-ismail/",
        google_scholar="https://scholar.google.com/citations?hl=en&user=DA68ObYAAAAJ",
        h_index=13,
        profile_uni_site="https://www.azraismail.me/apply",
        education_description="",
        extra_description="",
        academic_rank_id=3,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Mahdi",
        professor_m_name="S.",
        professor_l_name="Hosseini",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=8,
        department_id=2,
        email="mahdi.hosseini@concordia.ca",
        linkedin="https://www.linkedin.com/in/mahdi-s-hosseini-491719245/",
        google_scholar="https://scholar.google.com/citations?hl=en&user=SO-FFrgAAAAJ",
        h_index=15,
        profile_uni_site="https://www.concordia.ca/faculty/mahdi-hosseini.html",
        education_description="",
        extra_description="",
        academic_rank_id=3,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Dajiang",
        professor_m_name="",
        professor_l_name="Suo",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=9,
        department_id=2,
        email="dajiang.suo@asu.edu",
        linkedin="https://www.linkedin.com/in/dajiang-suo-7701a666/",
        google_scholar="https://scholar.google.com/citations?view_op=search_authors&hl=en&mauthors=Dajiang+Suo&btnG=",
        h_index=10,
        profile_uni_site="https://lnkd.in/g5pCBMqW",
        education_description="",
        extra_description="",
        academic_rank_id=3,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Seyede Fatemeh",
        professor_m_name="",
        professor_l_name="Ghoreishi",
        prof_gender=True,
        prof_code_in_uni=None,
        university_id=10,
        department_id=2,
        email="f.ghoreishi@northeastern.edu",
        linkedin="https://www.linkedin.com/in/fatemeh-ghoreishi-84708766/",
        google_scholar="https://scholar.google.com/citations?hl=en&user=BS8sZXgAAAAJ",
        h_index=17,
        profile_uni_site="https://ghoreishi.lab.northeastern.edu/",
        education_description="",
        extra_description="",
        academic_rank_id=3,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Erfan",
        professor_m_name="",
        professor_l_name="Nozari",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=11,
        department_id=2,
        email="erfan.nozari@ucr.edu",
        linkedin="https://www.linkedin.com/in/enozari/",
        google_scholar="https://scholar.google.com/citations?hl=en&user=4zyG-jcAAAAJ",
        h_index=13,
        profile_uni_site="https://intra.engr.ucr.edu/~enozari/",
        education_description="",
        extra_description="",
        academic_rank_id=3,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Ibrahim",
        professor_m_name="",
        professor_l_name="Sabek",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=12,
        department_id=2,
        email="sabek@usc.edu",
        linkedin="https://www.linkedin.com/in/ibrahim-sabek-52642223/",
        google_scholar="https://scholar.google.com/citations?hl=en&user=R8732voAAAAJ",
        h_index=12,
        profile_uni_site="https://lnkd.in/dBAa-dSE",
        education_description="",
        extra_description="",
        academic_rank_id=3,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Mohammad",
        professor_m_name="",
        professor_l_name="Mohammadi Amiri",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=13,
        department_id=2,
        email="mamiri@rpi.edu",
        linkedin="https://www.linkedin.com/in/mohammad-mohammadi-amiri-6a910754/",
        google_scholar="https://scholar.google.com/citations?hl=en&user=jpJy6SEAAAAJ",
        h_index=18,
        profile_uni_site="https://faculty.rpi.edu/mohammad-mohammadi-amiri",
        education_description="",
        extra_description="",
        academic_rank_id=3,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Swati",
        professor_m_name="",
        professor_l_name="Gupta",
        prof_gender=True,
        prof_code_in_uni=None,
        university_id=14,
        department_id=2,
        email="swatig@mit.edu",
        linkedin="https://linkedin.com/in/swati1729/",
        google_scholar="https://scholar.google.com/citations?hl=en&user=xFkDDLUAAAAJ",
        h_index=13,
        profile_uni_site="https://mitsloan.mit.edu/faculty/directory/swati-gupta",
        education_description="",
        extra_description="",
        academic_rank_id=3,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Rose",
        professor_m_name="",
        professor_l_name="Faghih",
        prof_gender=True,
        prof_code_in_uni=None,
        university_id=15,
        department_id=2,
        email="rtf3364@nyu.edu",
        linkedin="https://www.linkedin.com/in/rosefaghih/",
        google_scholar="https://scholar.google.com/citations?hl=en&user=Dzqq3MkAAAAJ",
        h_index=24,
        profile_uni_site="https://engineering.nyu.edu/faculty/rose-faghih",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Hao (Frank)",
        professor_m_name="",
        professor_l_name="Yang",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=16,
        department_id=2,
        email="jhufrankyang@gmail.com",
        linkedin="https://www.linkedin.com/in/hao-frank-yang-777218120/",
        google_scholar="https://scholar.google.com/citations?hl=en&user=IA_dRMIAAAAJ",
        h_index=13,
        profile_uni_site="https://www.haofrankyang.net/",
        education_description="",
        extra_description="",
        academic_rank_id=3,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Saleh",
        professor_m_name="",
        professor_l_name="Kalantari",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=17,
        department_id=2,
        email="sk3268@cornell.edu",
        linkedin="https://www.linkedin.com/in/saleh-kalantari-81aa1641/",
        google_scholar="https://scholar.google.com/citations?hl=en&user=xU-3sCQAAAAJ",
        h_index=15,
        profile_uni_site="https://www.human.cornell.edu/people/sk3268",
        education_description="",
        extra_description="",
        academic_rank_id=3,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Aman",
        professor_m_name="",
        professor_l_name="Arora",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=9,
        department_id=2,
        email="aman.kbm@asu.edu",
        linkedin="https://www.linkedin.com/in/amankbm/",
        google_scholar="https://scholar.google.com/citations?hl=en&user=xrJ1UEQAAAAJ",
        h_index=8,
        profile_uni_site="https://search.asu.edu/profile/4860216",
        education_description="",
        extra_description="",
        academic_rank_id=3,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Ciprian",
        professor_m_name="",
        professor_l_name="Alecsandru",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=8,
        department_id=3,
        email="Ciprian.Alecsandru@concordia.ca",
        linkedin="https://www.linkedin.com/in/alecsandru/",
        google_scholar="https://scholar.google.com/citations?hl=en&user=exRjZP8AAAAJ",
        h_index=11,
        profile_uni_site="https://www.concordia.ca/faculty/ciprian-alecsandru.html?c=/ginacody/building-civil-environmental-eng/about/faculty-members",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Chunjiang",
        professor_m_name="",
        professor_l_name="An",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=8,
        department_id=3,
        email="chunjiang.an@concordia.ca",
        linkedin="https://www.linkedin.com/in/chunjiang-an/",
        google_scholar="https://scholar.google.com/citations?hl=en&user=_uHWdnMAAAAJ",
        h_index=48,
        profile_uni_site="https://www.concordia.ca/faculty/chunjiang-an.html?c=/ginacody/building-civil-environmental-eng/about/faculty-members",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Eyosias",
        professor_m_name="",
        professor_l_name="Ashenafi",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=13,
        department_id=3,
        email=" ashene2@rpi.edu",
        linkedin="https://www.linkedin.com/in/eyosias/",
        google_scholar="https://scholar.google.com/citations?hl=en&user=7tLMyjUAAAAJ",
        h_index=4,
        profile_uni_site="https://faculty.rpi.edu/eyosias-ashenafi",
        education_description="",
        extra_description="",
        academic_rank_id=1,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Victoria",
        professor_m_name="",
        professor_l_name="Bennett",
        prof_gender=True,
        prof_code_in_uni=None,
        university_id=13,
        department_id=3,
        email="bennev@rpi.edu",
        linkedin="https://www.linkedin.com/in/victoria-bennett-5b4b127/",
        google_scholar="https://scholar.google.com/citations?hl=en&user=UBtYru0AAAAJ",
        h_index=15,
        profile_uni_site="https://faculty.rpi.edu/victoria-bennett",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Min",
        professor_m_name="",
        professor_l_name="Li",
        prof_gender=True,
        prof_code_in_uni=None,
        university_id=13,
        department_id=3,
        email="lim33@rpi.edu",
        linkedin="https://www.linkedin.com/in/min-li-a19529188/",
        google_scholar="",
        h_index=0,
        profile_uni_site="https://faculty.rpi.edu/min-li",
        education_description="",
        extra_description="",
        academic_rank_id=3,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Marianne",
        professor_m_name="",
        professor_l_name="Nyman",
        prof_gender=True,
        prof_code_in_uni=None,
        university_id=13,
        department_id=3,
        email="nymanm@rpi.edu",
        linkedin="https://www.linkedin.com/in/marianne-nieman-0613968/",
        google_scholar="https://scholar.google.com/citations?hl=en&user=4QPZurgAAAAJ",
        h_index=12,
        profile_uni_site="https://faculty.rpi.edu/marianne-nyman",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Cara",
        professor_m_name="",
        professor_l_name="Wang",
        prof_gender=True,
        prof_code_in_uni=None,
        university_id=13,
        department_id=3,
        email=" wangx18@rpi.edu",
        linkedin="https://www.linkedin.com/in/cara-wang-04463a24/",
        google_scholar="https://scholar.google.com/citations?hl=en&user=Fea2rDgAAAAJ",
        h_index=34,
        profile_uni_site="https://faculty.rpi.edu/cara-wang",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    # Anahita - 25 UK Data
    schemas.ProfessorCreate(
        professor_f_name="Kahtan",
        professor_m_name="",
        professor_l_name="Aziz",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=18,
        department_id=1,
        email="kahtan.aziz@aru.ac.uk",
        linkedin="https://uk.linkedin.com/in/kahtan-aziz-phd-fhea-smieee-miet-ceng-332b251?original_referer=https%3A%2F%2Fwww.google.com%2F",
        google_scholar="https://scholar.google.com/citations?user=81EFxX4AAAAJ&hl=en",
        h_index=7,
        profile_uni_site="https://www.aru.ac.uk/people/kahtan-aziz",
        education_description="",
        extra_description="",
        academic_rank_id=2,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Andrew",
        professor_m_name="",
        professor_l_name="Flewitt",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=19,
        department_id=1,
        email="ajf@eng.cam.ac.uk",
        linkedin="https://www.linkedin.com/in/andrew-flewitt-64253b164/",
        google_scholar="https://scholar.google.co.uk/citations?user=n786AZ8AAAAJ&hl=en",
        h_index=49,
        profile_uni_site="https://www.eng.cam.ac.uk/profiles/ajf23",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Ozgur",
        professor_m_name="B.",
        professor_l_name="Akan",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=19,
        department_id=1,
        email="oba21@eng.cam.ac.uk",
        linkedin="https://www.linkedin.com/in/%C3%B6zg%C3%BCr-bar%C4%B1%C5%9F-akan-90047a72",
        google_scholar="https://scholar.google.com/citations?user=H1dTZckAAAAJ&hl=en",
        h_index=62,
        profile_uni_site="https://www.eng.cam.ac.uk/profiles/oba21",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Gianna",
        professor_m_name="",
        professor_l_name="Bale",
        prof_gender=True,
        prof_code_in_uni=None,
        university_id=19,
        department_id=1,
        email="gmb49@eng.cam.ac.uk",
        linkedin="https://www.linkedin.com/in/gemma-bale-74b86441/",
        google_scholar="https://scholar.google.co.uk/citations?user=hY9aFz8AAAAJ&hl=en",
        h_index=15,
        profile_uni_site="https://www.eng.cam.ac.uk/profiles/gmb49",
        education_description="",
        extra_description="",
        academic_rank_id=3,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Tim",
        professor_m_name="",
        professor_l_name="Coombs",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=19,
        department_id=1,
        email="tac1000@eng.cam.ac.uk",
        linkedin="https://www.linkedin.com/in/tim-coombs-9806b37/",
        google_scholar="https://scholar.google.com/citations?user=XT-PQIAAAAAJ&hl=en",
        h_index=46,
        profile_uni_site="https://www.eng.cam.ac.uk/profiles/tac1000",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Martin",
        professor_m_name="",
        professor_l_name="booth",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=20,
        department_id=1,
        email="martin.booth@eng.ox.ac.uk",
        linkedin="https://www.linkedin.com/in/martin-booth-465214303/",
        google_scholar="https://scholar.google.com/citations?user=DP-Vq4sAAAAJ&hl=en",
        h_index=60,
        profile_uni_site="https://eng.ox.ac.uk/people/martin-booth/",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Adrew",
        professor_m_name="",
        professor_l_name="Markham",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=20,
        department_id=1,
        email="andrew.markham@cs.ox.ac.uk",
        linkedin="https://www.linkedin.com/in/andrew-markham-20029a44/",
        google_scholar="https://scholar.google.com/citations?user=g3JTO9EAAAAJ&hl=en",
        h_index=53,
        profile_uni_site="https://www.cs.ox.ac.uk/people/andrew.markham/",
        education_description="",
        extra_description="",
        academic_rank_id=1,
    ),
    schemas.ProfessorCreate(
        professor_f_name="wuqiang",
        professor_m_name="",
        professor_l_name="yang",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=21,
        department_id=1,
        email="wuqiang.yang@manchester.ac.uk",
        linkedin="https://www.linkedin.com/in/wuqiang-yang-751b537b/",
        google_scholar="https://scholar.google.com/citations?user=o64B21YAAAAJ&hl=en",
        h_index=53,
        profile_uni_site="https://research.manchester.ac.uk/en/persons/wuqiang.yang",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Fumie",
        professor_m_name="",
        professor_l_name="Costen",
        prof_gender=True,
        prof_code_in_uni=None,
        university_id=21,
        department_id=1,
        email="f.costen@cs.man.ac.uk",
        linkedin="https://www.linkedin.com/in/fumie-costen-9686271/",
        google_scholar="https://scholar.google.co.uk/citations?user=GKQnv50AAAAJ&hl=en",
        h_index=18,
        profile_uni_site="https://research.manchester.ac.uk/en/persons/fumie.costen",
        education_description="",
        extra_description="",
        academic_rank_id=1,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Theodoros",
        professor_m_name="",
        professor_l_name="Arvanitis",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=22,
        department_id=1,
        email="t.arvanitis@bham.ac.uk",
        linkedin="https://www.linkedin.com/in/theodoros-arvanitis-0a8266/",
        google_scholar="https://scholar.google.com/citations?user=SpS84lQAAAAJ&hl=en",
        h_index=48,
        profile_uni_site="https://www.birmingham.ac.uk/staff/profiles/eese/arvanitis-theodoros",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Oliver",
        professor_m_name="",
        professor_l_name="Allanson",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=22,
        department_id=1,
        email="o.d.allanson@bham.ac.uk",
        linkedin="https://www.linkedin.com/in/oliver-allanson-0205872a/",
        google_scholar="https://scholar.google.co.uk/citations?user=4Xx3muUAAAAJ&hl=en",
        h_index=13,
        profile_uni_site="https://www.birmingham.ac.uk/staff/profiles/eese/allanson-oliver",
        education_description="",
        extra_description="",
        academic_rank_id=3,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Chris",
        professor_m_name="",
        professor_l_name="Baker",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=22,
        department_id=1,
        email="c.j.baker.1@bham.ac.uk",
        linkedin="https://www.linkedin.com/in/chris-baker-6735371a/",
        google_scholar="https://scholar.google.com/citations?user=yw6Mo0wAAAAJ&hl=en",
        h_index=54,
        profile_uni_site="https://www.birmingham.ac.uk/staff/profiles/eese/baker-chris",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Mike",
        professor_m_name="",
        professor_l_name="Cherniakov",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=22,
        department_id=1,
        email="m.cherniakov@bham.ac.uk",
        linkedin="https://www.linkedin.com/in/mike-cherniakov-9847872b/",
        google_scholar="https://scholar.google.com/citations?user=la0fln0AAAAJ&hl=en",
        h_index=19,
        profile_uni_site="https://www.birmingham.ac.uk/staff/profiles/eese/cherniakov-mike",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Costas",
        professor_m_name="",
        professor_l_name="Constantinou",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=22,
        department_id=1,
        email="c.constantinou@bham.ac.uk",
        linkedin="https://www.linkedin.com/in/costas-constantinou-09697256/",
        google_scholar="https://scholar.google.com/citations?user=YNE_E2QAAAAJ&hl=en",
        h_index=24,
        profile_uni_site="https://www.birmingham.ac.uk/staff/profiles/eese/constantinou-costas",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Roger",
        professor_m_name="",
        professor_l_name="Dixon",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=22,
        department_id=1,
        email="r.dixon@bham.ac.uk",
        linkedin="https://www.linkedin.com/in/roger-dixon/?original_referer=https%3A%2F%2Fwww%2Egoogle%2Ecom%2F&originalSubdomain=uk",
        google_scholar="https://scholar.google.co.uk/citations?user=QnJlscAAAAAJ&hl=en",
        h_index=24,
        profile_uni_site="https://www.birmingham.ac.uk/staff/profiles/mechanical/dixon-roger",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Polina",
        professor_m_name="",
        professor_l_name="Bayvel",
        prof_gender=True,
        prof_code_in_uni=None,
        university_id=23,
        department_id=1,
        email="p.bayvel@ucl.ac.uk",
        linkedin="https://www.linkedin.com/in/polina-bayvel-90604a13/",
        google_scholar="https://scholar.google.com/citations?user=OvvW5XUAAAAJ&hl=en",
        h_index=56,
        profile_uni_site="https://www.ucl.ac.uk/iccs/prof-polina-bayvel",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Alejandra",
        professor_m_name="",
        professor_l_name="Beghelli",
        prof_gender=True,
        prof_code_in_uni=None,
        university_id=23,
        department_id=1,
        email="alejandra.beghelli@ucl.ac.uk",
        linkedin="https://www.linkedin.com/in/alejandrabeghelli/?original_referer=https%3A%2F%2Fwww%2Egoogle%2Ecom%2F&originalSubdomain=uk",
        google_scholar="https://scholar.google.com/citations?user=kP8pBuEAAAAJ&hl=en",
        h_index=14,
        profile_uni_site="https://www.ucl.ac.uk/iccs/dr-alejandra-beghelli",
        education_description="",
        extra_description="",
        academic_rank_id=1,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Neil",
        professor_m_name="",
        professor_l_name="Curson",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=23,
        department_id=1,
        email="n.curson@ucl.ac.uk",
        linkedin="https://www.linkedin.com/in/neil-curson-826067b/",
        google_scholar="https://scholar.google.com/citations?user=WPjzrnoAAAAJ&hl=en",
        h_index=30,
        profile_uni_site="https://www.ucl.ac.uk/electronic-electrical-engineering/people/dr-neil-curson",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Charles",
        professor_m_name="",
        professor_l_name="Augrade",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=24,
        department_id=3,
        email="charles.augarde@durham.ac.uk",
        linkedin="https://www.linkedin.com/in/charles-augarde-1664769/",
        google_scholar="https://scholar.google.com/citations?user=ybc-VSMAAAAJ&hl=en",
        h_index=44,
        profile_uni_site="https://www.durham.ac.uk/staff/charles-augarde/",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Madhu",
        professor_m_name="Sudana",
        professor_l_name="Reddy",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=20,
        department_id=2,
        email="srinamasa@gmail.com",
        linkedin="https://www.linkedin.com/in/dr-madhu-reddy-22410581/",
        google_scholar="https://scholar.google.com/citations?user=d5nD8uoAAAAJ&hl=en",
        h_index=9,
        profile_uni_site="http://www.theoxfordengg.org/department-mechanical-engineering.htm",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Michael",
        professor_m_name="",
        professor_l_name="Sutcliffe",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=19,
        department_id=2,
        email="mpfs@eng.cam.ac.uk",
        linkedin="https://www.linkedin.com/in/michael-sutcliffe-840910103/",
        google_scholar="https://scholar.google.com/citations?user=xXU7cLgAAAAJ&hl=en",
        h_index=41,
        profile_uni_site="https://www.eng.cam.ac.uk/profiles/mpfs1",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Tom",
        professor_m_name="",
        professor_l_name="Bashford",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=19,
        department_id=2,
        email="tb508@eng.cam.ac.uk",
        linkedin="https://www.linkedin.com/in/tom-bashford-506165277/",
        google_scholar="https://scholar.google.com/citations?user=9i92dKYAAAAJ&hl=en",
        h_index=14,
        profile_uni_site="https://www.eng.cam.ac.uk/profiles/tb508",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="John",
        professor_m_name="S.",
        professor_l_name="Biggin",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=19,
        department_id=2,
        email="tb508@eng.cam.ac.uk",
        linkedin="https://www.linkedin.com/in/john-biggins-0a3b184/",
        google_scholar="https://scholar.google.co.uk/citations?user=J5TlRyEAAAAJ&hl=en",
        h_index=21,
        profile_uni_site="https://www.eng.cam.ac.uk/profiles/jsb56",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="David",
        professor_m_name="",
        professor_l_name="Cardwell",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=19,
        department_id=2,
        email="david.cardwell@admin.cam.ac.uk",
        linkedin="https://www.linkedin.com/in/david-cardwell-81b17631/",
        google_scholar="https://scholar.google.com/citations?user=yhPKfnoAAAAJ&hl=en",
        h_index=44,
        profile_uni_site="http://bulk-sucon.eng.cam.ac.uk/dc135/",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Nathan",
        professor_m_name="",
        professor_l_name="Crilly",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=19,
        department_id=2,
        email="nc266@eng.cam.ac.uk",
        linkedin="https://www.linkedin.com/in/nathancrilly/?originalSubdomain=uk",
        google_scholar="https://scholar.google.co.uk/citations?user=sl5HOpIAAAAJ&hl=en",
        h_index=28,
        profile_uni_site="https://www.eng.cam.ac.uk/profiles/nc266",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    # Sepehr - 25 FRG(Germany) Data
    schemas.ProfessorCreate(
        professor_f_name="Ralf",
        professor_m_name="",
        professor_l_name="Brederlow",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=25,
        department_id=1,
        email="r.brederlow@tum.de",
        linkedin="https://www.linkedin.com/in/ralf-brederlow-135a13/",
        google_scholar="https://scholar.google.de/citations?user=w3aCbjAAAAAJ&hl=en",
        h_index=30,
        profile_uni_site="https://campus.tum.de/tumonline/ee/ui/ca2/app/desktop/#/pl/ui/$ctx/visitenkarte.show_vcard?$ctx=design=ca2;header=max;lang=de&pPersonenGruppe=3&pPersonenId=51DB7CF35234DDFF",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Ghulam",
        professor_m_name="",
        professor_l_name="Destgeer",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=25,
        department_id=1,
        email="ghulam.destgeer@tum.de",
        linkedin="https://www.linkedin.com/in/destgeer/",
        google_scholar="https://scholar.google.it/citations?user=J4PQKMgAAAAJ&hl=en",
        h_index=28,
        profile_uni_site="https://campus.tum.de/tumonline/ee/ui/ca2/app/desktop/#/pl/ui/$ctx/visitenkarte.show_vcard?$ctx=design=ca2;header=max;lang=de&pPersonenGruppe=3&pPersonenId=C8319F75D6115C7B",
        education_description="",
        extra_description="",
        academic_rank_id=3,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Jia",
        professor_m_name="",
        professor_l_name="Chen",
        prof_gender=True,
        prof_code_in_uni=None,
        university_id=25,
        department_id=1,
        email="jia.chen@tum.de",
        linkedin="https://www.linkedin.com/in/jia-chen-328a6917/",
        google_scholar="https://scholar.google.com/citations?user=HvhVcFsAAAAJ&hl=en",
        h_index=30,
        profile_uni_site="https://campus.tum.de/tumonline/ee/ui/ca2/app/desktop/#/pl/ui/$ctx/visitenkarte.show_vcard?$ctx=design=ca2;header=max;lang=de&pPersonenGruppe=3&pPersonenId=1FFCB0A4079A2968",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Maribel",
        professor_m_name="",
        professor_l_name="Acosta Deibe",
        prof_gender=True,
        prof_code_in_uni=None,
        university_id=25,
        department_id=4,
        email="maribel.acosta@tum.de",
        linkedin="https://www.linkedin.com/in/maribel-acosta-deibe-83b80a3b/",
        google_scholar="https://scholar.google.de/citations?user=druU9nsAAAAJ&hl=en",
        h_index=15,
        profile_uni_site="https://campus.tum.de/tumonline/ee/ui/ca2/app/desktop/#/pl/ui/$ctx/visitenkarte.show_vcard?$ctx=design=ca2;header=max;lang=de&pPersonenGruppe=3&pPersonenId=991E7768FD13FD70",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Hartwig",
        professor_m_name="",
        professor_l_name="Anzt",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=25,
        department_id=4,
        email="hartwig.anzt@tum.de",
        linkedin="https://www.linkedin.com/in/hartwig-anzt-a1997566/",
        google_scholar="https://scholar.google.com/citations?user=ctNCF8YAAAAJ&hl=de",
        h_index=30,
        profile_uni_site="https://campus.tum.de/tumonline/ee/ui/ca2/app/desktop/#/pl/ui/$ctx/visitenkarte.show_vcard?$ctx=design=ca2;header=max;lang=de&pPersonenGruppe=3&pPersonenId=72BFB36BA19D260C",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Daniel",
        professor_m_name="",
        professor_l_name="Cremers",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=25,
        department_id=4,
        email="cremers@tum.de",
        linkedin="https://www.linkedin.com/in/daniel-cremers/",
        google_scholar="https://scholar.google.com/citations?user=cXQciMEAAAAJ&hl=en",
        h_index=118,
        profile_uni_site="https://campus.tum.de/tumonline/ee/ui/ca2/app/desktop/#/pl/ui/$ctx/visitenkarte.show_vcard?$ctx=design=ca2;header=max;lang=de&pPersonenGruppe=3&pPersonenId=B53F0E7568B34CDA",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Jalal",
        professor_m_name="",
        professor_l_name="Etesami",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=25,
        department_id=4,
        email="j.etesami@tum.de",
        linkedin="https://www.linkedin.com/in/jalal-etesami-586a82146/",
        google_scholar="https://scholar.google.com/citations?user=3Usg1G0AAAAJ&hl=en",
        h_index=11,
        profile_uni_site="https://campus.tum.de/tumonline/ee/ui/ca2/app/desktop/#/pl/ui/$ctx/visitenkarte.show_vcard?$ctx=design=ca2;header=max;lang=de&pPersonenGruppe=3&pPersonenId=11582B8747F1A812",
        education_description="",
        extra_description="",
        academic_rank_id=3,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Andre",
        professor_m_name="",
        professor_l_name="Borrmann",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=25,
        department_id=3,
        email="andre.borrmann@tum.de",
        linkedin="https://www.linkedin.com/in/andr%C3%A9-borrmann-b91a2127/",
        google_scholar="https://scholar.google.com/citations?user=9LSpz44AAAAJ&hl=en",
        h_index=46,
        profile_uni_site="https://campus.tum.de/tumonline/visitenkarte.show_vcard?pPersonenId=99840C4AF3F72BA9&pPersonenGruppe=3",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Johannes",
        professor_m_name="",
        professor_l_name="Fottner",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=25,
        department_id=2,
        email="j.fottner@tum.de",
        linkedin="https://www.linkedin.com/in/johannes-fottner-25b5245/",
        google_scholar="https://scholar.google.com/citations?user=dRvevgQAAAAJ&hl=en",
        h_index=14,
        profile_uni_site="https://campus.tum.de/tumonline/visitenkarte.show_vcard?pPersonenId=21A593B1F5C48351&pPersonenGruppe=3",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Zahra",
        professor_m_name="",
        professor_l_name="Amini Farsani",
        prof_gender=True,
        prof_code_in_uni=None,
        university_id=26,
        department_id=4,
        email="Zahra.Farsani@stat.uni-muenchen.de",
        linkedin="https://www.linkedin.com/in/zahra-aminifarsani-0748aa290/",
        google_scholar="https://scholar.google.com/citations?user=fhAZ6DUAAAAJ&hl=en",
        h_index=4,
        profile_uni_site="https://www.m-datascience.mathematik-informatik-statistik.uni-muenchen.de/People/professors/zahra/index.html",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Katinka",
        professor_m_name="",
        professor_l_name="Wolter",
        prof_gender=True,
        prof_code_in_uni=None,
        university_id=27,
        department_id=4,
        email="katinka.wolter@fu-berlin.de",
        linkedin="https://www.linkedin.com/in/katinka-wolter-60045731/",
        google_scholar="https://scholar.google.at/citations?user=JqtocLYAAAAJ&hl=de",
        h_index=32,
        profile_uni_site="https://www.mi.fu-berlin.de/inf/groups/ag-dds/staff/wolter.html",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Tim",
        professor_m_name="",
        professor_l_name="Landgraf",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=27,
        department_id=4,
        email="tim.landgraf@fu-berlin.de",
        linkedin="https://www.linkedin.com/in/tim-landgraf-6655056/",
        google_scholar="https://scholar.google.de/citations?user=ChX0opIAAAAJ&hl=en",
        h_index=24,
        profile_uni_site="https://www.mi.fu-berlin.de/inf/groups/ag-ki/members/Professoren/Tim_Landgraf.html",
        education_description="",
        extra_description="",
        academic_rank_id=3,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Knut",
        professor_m_name="",
        professor_l_name="Reinert",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=27,
        department_id=4,
        email="knut.reinert@fu-berlin.de",
        linkedin="https://www.linkedin.com/in/knut-reinert-8287774/",
        google_scholar="https://scholar.google.com/citations?user=XwG4wAcAAAAJ&hl=en",
        h_index=55,
        profile_uni_site="https://www.mi.fu-berlin.de/en/inf/groups/abi/members/Professors/reinert.html",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Sahin",
        professor_m_name="",
        professor_l_name="Albayrak",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=28,
        department_id=4,
        email="sahin.albayrak@dai-labor.de",
        linkedin="https://www.linkedin.com/in/sahin-albayrak-35640b/",
        google_scholar="https://scholar.google.de/citations?user=K7BOZUAAAAAJ&hl=en",
        h_index=43,
        profile_uni_site="https://dai-labor.de/en/team/sahin-albayrak-2/",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Falko",
        professor_m_name="",
        professor_l_name="Dressler",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=28,
        department_id=1,
        email="dressler@tu-berlin.de",
        linkedin="https://www.linkedin.com/in/falko-dressler-aa53b0211/",
        google_scholar="https://scholar.google.com/citations?user=sK8213AAAAAJ&hl=en",
        h_index=62,
        profile_uni_site="https://www.tu.berlin/en/tkn/about/head",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Corrado",
        professor_m_name="",
        professor_l_name="Carta",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=28,
        department_id=1,
        email="corrado.carta@tu-berlin.de",
        linkedin="https://www.linkedin.com/in/corradocarta/",
        google_scholar="https://scholar.google.com/citations?user=9SKceHQAAAAJ&hl=en",
        h_index=26,
        profile_uni_site="https://www.tu.berlin/en/vcard/corrado.carta",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Sibylle",
        professor_m_name="",
        professor_l_name="Dieckerhoff",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=28,
        department_id=1,
        email="sibylle.dieckerhoff@tu-berlin.de",
        linkedin="https://www.linkedin.com/in/sibylle-dieckerhoff-347881205/",
        google_scholar="https://scholar.google.com/citations?user=BCqwgdUAAAAJ&hl=de",
        h_index=21,
        profile_uni_site="https://www.tu.berlin/en/pe/about/management-and-administration/prof-dr-ing-sibylle-dieckerhoff",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Manfred",
        professor_m_name="",
        professor_l_name="Hauswirth",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=28,
        department_id=1,
        email="manfred.hauswirth@fokus.fraunhofer.de",
        linkedin="https://www.linkedin.com/in/manfredhauswirth/",
        google_scholar="https://scholar.google.com/citations?user=WwjTJ3YAAAAJ&hl=en",
        h_index=57,
        profile_uni_site="https://www.tu.berlin/en/ods/about-us/prof-dr-manfred-hauswirth",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Priyamvada",
        professor_m_name="",
        professor_l_name="Jadaun",
        prof_gender=True,
        prof_code_in_uni=None,
        university_id=28,
        department_id=1,
        email="priyamvadaj@gmail.com",
        linkedin="https://www.linkedin.com/in/priyamvada-jadaun-146452a/",
        google_scholar="https://scholar.google.com/citations?user=2LvYFWcAAAAJ&hl=en",
        h_index=11,
        profile_uni_site="https://www.tu.berlin/en/sam",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="John",
        professor_m_name="",
        professor_l_name="Jelonnek",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=29,
        department_id=1,
        email="john.jelonnek@kit.edu",
        linkedin="https://www.linkedin.com/in/john-jelonnek-6705241a/",
        google_scholar="https://scholar.google.com.au/citations?user=LAognVYAAAAJ&hl=en",
        h_index=29,
        profile_uni_site="https://www.etit.kit.edu/english/professor_innen_1320.php",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Uli",
        professor_m_name="",
        professor_l_name="Lemmer",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=29,
        department_id=1,
        email="Uli.Lemmer@kit.edu",
        linkedin="https://www.linkedin.com/in/uli-lemmer-3a55674/",
        google_scholar="https://scholar.google.com/citations?user=0tmWfIAAAAAJ&hl=en",
        h_index=81,
        profile_uni_site="https://www.etit.kit.edu/english/professor_innen_315.php",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Peter",
        professor_m_name="",
        professor_l_name="Rost",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=29,
        department_id=1,
        email="peter.rost@kit.edu",
        linkedin="https://www.linkedin.com/in/peter-rost-0209418/",
        google_scholar="https://scholar.google.com/citations?user=DIvDzMsAAAAJ&hl=en",
        h_index=28,
        profile_uni_site="https://www.etit.kit.edu/english/professor_innen_3422.php",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Wilhelm",
        professor_m_name="",
        professor_l_name="Stork",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=29,
        department_id=1,
        email="Wilhelm.Stork@kit.edu",
        linkedin="https://www.linkedin.com/in/wilhelm-stork-1a604b1a/",
        google_scholar="https://scholar.google.de/citations?user=Ygptk90AAAAJ&hl=de",
        h_index=28,
        profile_uni_site="https://www.etit.kit.edu/english/professor_innen_524.php",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Christian",
        professor_m_name="",
        professor_l_name="Koos",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=29,
        department_id=1,
        email="Christian.Koos@kit.edu",
        linkedin="https://www.linkedin.com/in/christian-koos-158a0694/",
        google_scholar="https://scholar.google.com/citations?user=nVB2magAAAAJ&hl=en",
        h_index=64,
        profile_uni_site="https://www.etit.kit.edu/english/professor_innen_949.php",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Michael",
        professor_m_name="",
        professor_l_name="Heizmann",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=29,
        department_id=1,
        email="Michael.Heizmann@kit.edu",
        linkedin="https://www.linkedin.com/in/michael-heizmann-1341212a1/",
        google_scholar="https://scholar.google.com.au/citations?user=OZ6vEpcAAAAJ&hl=en",
        h_index=19,
        profile_uni_site="https://www.etit.kit.edu/english/professor_innen_1511.php",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    # Nima - Canada
    schemas.ProfessorCreate(
        professor_f_name="Mireille",
        professor_m_name="E.",
        professor_l_name="Broucke",
        prof_gender=True,
        prof_code_in_uni=None,
        university_id=33,
        department_id=1,
        email="broucke@control.utoronto.ca",
        linkedin="",
        google_scholar="https://scholar.google.com/citations?user=oa4wmioAAAAJ&hl=en",
        h_index=25,
        profile_uni_site="https://www.ece.utoronto.ca/people/broucke-m/",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Margaret",
        professor_m_name="",
        professor_l_name="Chapman",
        prof_gender=True,
        prof_code_in_uni=None,
        university_id=33,
        department_id=1,
        email="mchapman@ece.utoronto.ca",
        linkedin="https://www.linkedin.com/in/margaret-p-chapman-phd-006993220/",
        google_scholar="https://scholar.google.com/citations?user=muxEukIAAAAJ&hl=en",
        h_index=10,
        profile_uni_site="https://www.ece.utoronto.ca/people/chapman-m/",
        education_description="",
        extra_description="",
        academic_rank_id=3,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Manfredi",
        professor_m_name="",
        professor_l_name="Maggiore",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=33,
        department_id=1,
        email="maggiore@control.utoronto.ca",
        linkedin="",
        google_scholar="https://scholar.google.com/citations?user=Yw-4uyoAAAAJ&hl=en",
        h_index=27,
        profile_uni_site="https://www.ece.utoronto.ca/people/maggiore-m/",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Lacra",
        professor_m_name="",
        professor_l_name="Pavel",
        prof_gender=True,
        prof_code_in_uni=None,
        university_id=33,
        department_id=1,
        email="pavel@control.utoronto.ca",
        linkedin="https://www.linkedin.com/in/lacra-pavel-a2a30a57/?original_referer=https%3A%2F%2Fwww%2Egoogle%2Ecom%2F&originalSubdomain=ca",
        google_scholar="https://scholar.google.ca/citations?user=p1ckG-0AAAAJ&hl=en",
        h_index=30,
        profile_uni_site="https://www.ece.utoronto.ca/people/pavel-l/",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Luca",
        professor_m_name="",
        professor_l_name="Scardovi",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=33,
        department_id=1,
        email="scardovi@ece.utoronto.ca",
        linkedin="https://www.linkedin.com/in/luca-scardovi-55b97342?originalSubdomain=ca",
        google_scholar="https://scholar.google.com/citations?user=beMSE0sAAAAJ",
        h_index=20,
        profile_uni_site="https://www.control.utoronto.ca/~scardovi//",
        education_description="",
        extra_description="",
        academic_rank_id=4,
    ),
    schemas.ProfessorCreate(
        professor_f_name="John",
        professor_m_name="W.",
        professor_l_name="Simpson-Porco",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=33,
        department_id=1,
        email="jwsimpson@ece.utoronto.ca",
        linkedin="https://www.linkedin.com/in/john-simpson-porco-49401b24?original_referer=https%3A%2F%2Fwww%2Egoogle%2Ecom%2F&originalSubdomain=ca",
        google_scholar="https://scholar.google.com/citations?user=tyQhs60AAAAJ&hl=en",
        h_index=34,
        profile_uni_site="https://www.ece.utoronto.ca/people/simpson-porco-j/",
        education_description="",
        extra_description="",
        academic_rank_id=3,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Parham",
        professor_m_name="",
        professor_l_name="Aarabi",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=33,
        department_id=1,
        email="p@arh.am",
        linkedin="https://www.linkedin.com/in/parhamaarabi/?originalSubdomain=ca",
        google_scholar="https://scholar.google.com/citations?user=Vqr5M1YAAAAJ&hl=en",
        h_index=33,
        profile_uni_site="https://www.ece.utoronto.ca/people/aarabi-p/",
        education_description="",
        extra_description="",
        academic_rank_id=4,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Steve",
        professor_m_name="",
        professor_l_name="Mann",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=33,
        department_id=1,
        email="mann@eecg.toronto.edu",
        linkedin="https://www.linkedin.com/in/steve-mann-8560b495/?original_referer=https%3A%2F%2Fwww%2Egoogle%2Ecom%2F&originalSubdomain=ca",
        google_scholar="https://scholar.google.ca/citations?user=7bmQ4FgAAAAJ&hl=en",
        h_index=62,
        profile_uni_site="https://www.ece.utoronto.ca/people/mann-s/",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Jonathan",
        professor_m_name="",
        professor_l_name="Rose",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=33,
        department_id=1,
        email="Jonathan.Rose@ece.utoronto.ca",
        linkedin="https://www.linkedin.com/in/jonathanrose2/?originalSubdomain=ca",
        google_scholar="https://scholar.google.com/citations?user=Icox8ecAAAAJ&hl=en",
        h_index=65,
        profile_uni_site="https://www.ece.utoronto.ca/people/rose-j-s/",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Salma",
        professor_m_name="",
        professor_l_name="Emara",
        prof_gender=True,
        prof_code_in_uni=None,
        university_id=33,
        department_id=1,
        email="salma@ece.utoronto.ca",
        linkedin="https://www.linkedin.com/in/salma-emara-b37802a9/?original_referer=https%3A%2F%2Fwww%2Egoogle%2Ecom%2F&originalSubdomain=ca",
        google_scholar="https://scholar.google.com/citations?user=lg7XTfYAAAAJ&hl=en",
        h_index=5,
        profile_uni_site="https://www.ece.utoronto.ca/people/emara-s/",
        education_description="",
        extra_description="",
        academic_rank_id=3,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Tor",
        professor_m_name="",
        professor_l_name="Aamodt",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=34,
        department_id=1,
        email="aamodt@ece.ubc.ca",
        linkedin="https://ca.linkedin.com/in/tor-aamodt-2811564",
        google_scholar="https://scholar.google.com/citations?user=zCsB5XsAAAAJ&hl=en",
        h_index=40,
        profile_uni_site="https://ece.ubc.ca/tor-aaamodt/",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Sidney",
        professor_m_name="",
        professor_l_name="Fels",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=34,
        department_id=1,
        email="ssfels@ece.ubc.ca",
        linkedin="https://www.linkedin.com/in/sidney-fels-3160061/",
        google_scholar="https://scholar.google.com/citations?user=bf7ilxMAAAAJ&hl=en",
        h_index=51,
        profile_uni_site="https://ece.ubc.ca/sid-fels/",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Cristian",
        professor_m_name="Sorin",
        professor_l_name="Grecu",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=34,
        department_id=1,
        email="grecuc@ece.ubc.ca",
        linkedin="https://ca.linkedin.com/in/cristian-grecu-0507374",
        google_scholar="https://scholar.google.ca/citations?user=-H-yOt4AAAAJ&hl=en",
        h_index=25,
        profile_uni_site="https://ece.ubc.ca/cristian-sorin-grecu/",
        education_description="",
        extra_description="",
        academic_rank_id=6,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Alexandra",
        professor_m_name="Sash",
        professor_l_name="Fedorova",
        prof_gender=True,
        prof_code_in_uni=None,
        university_id=34,
        department_id=1,
        email="sasha@ece.ubc.ca",
        linkedin="https://ca.linkedin.com/in/alexandrafedorova",
        google_scholar="https://scholar.google.ca/citations?user=orMwSjoAAAAJ&hl=en",
        h_index=42,
        profile_uni_site="https://ece.ubc.ca/alexandra-sasha-fedorova/",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Carol",
        professor_m_name="",
        professor_l_name="Jaeger",
        prof_gender=True,
        prof_code_in_uni=None,
        university_id=34,
        department_id=1,
        email="carolj@ece.ubc.ca",
        linkedin="",
        google_scholar="https://scholar.google.com/citations?user=uSUf2MIAAAAJ&hl=en",
        h_index=4,
        profile_uni_site="https://ece.ubc.ca/carol-jaeger/",
        education_description="",
        extra_description="",
        academic_rank_id=7,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Audrey",
        professor_m_name="A.",
        professor_l_name="Sedal",
        prof_gender=True,
        prof_code_in_uni=None,
        university_id=35,
        department_id=2,
        email="audrey.sedal@mcgill.ca",
        linkedin="https://www.linkedin.com/in/audrey-sedal-11319057/?originalSubdomain=ca",
        google_scholar="https://scholar.google.com/citations?user=FPtpy7gAAAAJ&hl=en",
        h_index=8,
        profile_uni_site="https://www.mcgill.ca/mecheng/audrey-sedal",
        education_description="",
        extra_description="",
        academic_rank_id=3,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Inna",
        professor_m_name="",
        professor_l_name="Sharf",
        prof_gender=True,
        prof_code_in_uni=None,
        university_id=35,
        department_id=2,
        email="inna.sharf@mcgill.ca",
        linkedin="https://www.linkedin.com/in/inna-sharf-528b8621/?original_referer=https%3A%2F%2Fwww%2Egoogle%2Ecom%2F&originalSubdomain=ca",
        google_scholar="https://scholar.google.ca/citations?user=Ys2mNPkAAAAJ&hl=en",
        h_index=37,
        profile_uni_site="https://www.mcgill.ca/mecheng/inna-sharf",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Yaoyao",
        professor_m_name="Fiona",
        professor_l_name="Zhao",
        prof_gender=True,
        prof_code_in_uni=None,
        university_id=35,
        department_id=2,
        email="yaoyao.zhao@mcgill.ca",
        linkedin="https://www.linkedin.com/in/fiona-zhao-4541a912/?originalSubdomain=ca",
        google_scholar="https://scholar.google.ca/citations?user=Z3GXcjgAAAAJ&hl=en",
        h_index=45,
        profile_uni_site="https://www.mcgill.ca/mecheng/yaoyao-zhao",
        education_description="",
        extra_description="",
        academic_rank_id=4,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Marco",
        professor_m_name="",
        professor_l_name="Amabili",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=35,
        department_id=2,
        email="marco.amabili@mcgill.ca",
        linkedin="https://www.linkedin.com/in/marco-am-4b1839252/?originalSubdomain=ca",
        google_scholar="https://scholar.google.com/citations?user=m-tvN9kAAAAJ&hl=en",
        h_index=77,
        profile_uni_site="https://www.mcgill.ca/mecheng/marco-amabili",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Mathieu",
        professor_m_name=" ",
        professor_l_name="Francoeur",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=35,
        department_id=2,
        email="mathieu.francoeur@mcgill.ca",
        linkedin="",
        google_scholar="https://scholar.google.com/citations?user=lpQlXsYAAAAJ&hl=en",
        h_index=31,
        profile_uni_site="https://mcgill.ca/mecheng/mathieu-francoeur",
        education_description="",
        extra_description="",
        academic_rank_id=4,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Jeffrey",
        professor_m_name="",
        professor_l_name="Bergthorson",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=35,
        department_id=2,
        email="jeff.bergthorson@mcgill.ca",
        linkedin="https://www.linkedin.com/in/jeff-bergthorson-66913924/?original_referer=https%3A%2F%2Fwww%2Egoogle%2Ecom%2F&originalSubdomain=ca",
        google_scholar="https://scholar.google.com/citations?user=0L0H7BcAAAAJ&hl=en",
        h_index=43,
        profile_uni_site="https://www.mcgill.ca/mecheng/jeffrey-bergthorson",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Tal",
        professor_m_name="",
        professor_l_name="Arbel",
        prof_gender=True,
        prof_code_in_uni=None,
        university_id=35,
        department_id=1,
        email="tal.arbel@mcgill.ca",
        linkedin="https://www.linkedin.com/in/tal-arbel-a5b391143/?originalSubdomain=ca",
        google_scholar="https://scholar.google.com/citations?user=0AN34NMAAAAJ&hl=en",
        h_index=42,
        profile_uni_site="https://www.mcgill.ca/ece/tal-arbel",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Benoit",
        professor_m_name="",
        professor_l_name="Boulet",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=35,
        department_id=1,
        email="benoit.boulet@mcgill.ca",
        linkedin="https://www.linkedin.com/in/benoit-boulet-97078012/?originalSubdomain=ca",
        google_scholar="https://scholar.google.ca/citations?user=kkGyLY4AAAAJ&hl=en",
        h_index=31,
        profile_uni_site="https://www.mcgill.ca/ece/benoit-boulet",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Jeremy",
        professor_m_name="",
        professor_l_name="Cooperstock",
        prof_gender=False,
        prof_code_in_uni=None,
        university_id=35,
        department_id=1,
        email="jeremy.cooperstock@mcgill.ca",
        linkedin="https://www.linkedin.com/in/jeremy-cooperstock-46561a24/?originalSubdomain=ca",
        google_scholar="https://scholar.google.com/citations?user=QnLo6bAAAAAJ&hl=en",
        h_index=39,
        profile_uni_site="https://www.mcgill.ca/ece/jeremy-cooperstock",
        education_description="",
        extra_description="",
        academic_rank_id=5,
    ),
    schemas.ProfessorCreate(
        professor_f_name="Narges",
        professor_m_name="",
        professor_l_name="Armanfard",
        prof_gender=True,
        prof_code_in_uni=None,
        university_id=35,
        department_id=1,
        email="narges.armanfard@mcgill.ca",
        linkedin="https://www.linkedin.com/in/armanfardn/?originalSubdomain=ca",
        google_scholar="https://scholar.google.com/citations?user=V8pn4tIAAAAJ&hl=en",
        h_index=16,
        profile_uni_site="https://ismart.ece.mcgill.ca//",
        education_description="",
        extra_description="",
        academic_rank_id=4,
    ),
]


def add_professor_seed_data(db: Session):
    if not crud.professor.get_all(db):
        for data in professor_seed_data:
            crud.professor.create(db, data)
