from .academic_rank import *
from .city import *
from .country import *
from .department import *
from .fund import *
from .item import *
from .position import *
from .position_type import *
from .prof_interest import *
from .professor import *
from .research_interest import *
from .token import *
from .university import *
from .user import *
